### ISSUE TITLE
CoqUtils version

### ISSUE THREAD

**Issue by chaomaer** [arthuraa/memory-safe-language#1]
Coq 8.6
MathComp 1.6

I try to build this project using CoqUtils (latest version of branch domain), but the CoqUtils fails to build. and I choose CoqUtils of brach master with commit-id 82e45d3, CoqUtils build successfully but memory-safe-language still fail to build. which version of CoqUtils should i use to build this project? thank you.

**Comment by arthuraa** [comment]
Thanks for reminding me of this. I had split parts of CoqUtils into the extructures library (https://github.com/arthuraa/extructures), but ended up not updating this development. It should be compiling with the most recent versions now.
