### ISSUE TITLE
Theory.ler_total was not found.

### ISSUE THREAD

**Issue by selenelinares** [arthuraa/memory-safe-language#2]
Hi.

When I try to compile the project, I get this error: 
`
File "./basic.v", line 23, characters 21-41: 
Error: The reference Num.Theory.ler_total
was not found in the current environment. `

Versions installed:
- Coq 8.11.0
- deriving & extructures dev version
- mathcomp 1.11.0

It seems that `ler_total` is found in `mathcomp v1.10.0`  however, if I downgrade to that version, the `deriving` library doesn't compile. 
Could you please help me to solve this?

Thank you.

**Comment by arthuraa** [comment]
Thanks for reporting this. I have just updated the development to the newest versions of all the libraries. In case you use Nix, I have also added a shell file that automatically sets up an environment for you. Let me know if this works for you.

**Comment by selenelinares** [comment]
Thanks for your help, Arthur. It works now.
